# Generated by Django 3.1.7 on 2021-03-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0004_auto_20210313_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='netflix.Category'),
        ),
    ]
